/**
 * Lethean Binary API
 * Functionality to simplify using LTHN
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef lthnSDP_OBJECT_H
#define lthnSDP_OBJECT_H

#include <QJsonDocument>
#include <QJsonObject>
#include <QMetaType>

namespace lthn {
namespace sdp {
namespace api {

class lthnSDPObject {
public:
    lthnSDPObject() {}

    lthnSDPObject(QString jsonString) {
        fromJson(jsonString);
    }

    virtual ~lthnSDPObject() {}

    virtual QJsonObject asJsonObject() const {
        return jObj;
    }

    virtual QString asJson() const {
        QJsonDocument doc(jObj);
        return doc.toJson(QJsonDocument::Compact);
    }

    virtual void fromJson(QString jsonString) {
        QJsonDocument doc = QJsonDocument::fromJson(jsonString.toUtf8());
        jObj = doc.object();
    }

    virtual void fromJsonObject(QJsonObject json) {
        jObj = json;
    }

    virtual bool isSet() const {
        return false;
    }

    virtual bool isValid() const {
        return true;
    }

private:
    QJsonObject jObj;
};

} // namespace lthn
} // namespace sdp
} // namespace api

Q_DECLARE_METATYPE(lthn::sdp::api::lthnSDPObject)

#endif // lthnSDP_OBJECT_H
